using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Genesis.Net.Common;

namespace Fibonatix.CommDoo.Helpers
{
    public class Currencies
    {
        public static Iso4217CurrencyCodes currencyCodeFromString(string c) {
            if (c == null) return Iso4217CurrencyCodes.Undefined;
            string code = c.ToUpper();
            if (code == "AED") return Iso4217CurrencyCodes.AED;
            else if (code == "AFN") return Iso4217CurrencyCodes.AFN;
            else if (code == "ANG") return Iso4217CurrencyCodes.ANG;
            else if (code == "ALL") return Iso4217CurrencyCodes.ALL;
            else if (code == "AMD") return Iso4217CurrencyCodes.AMD;
            else if (code == "AOA") return Iso4217CurrencyCodes.AOA;
            else if (code == "ARS") return Iso4217CurrencyCodes.ARS;
            else if (code == "AUD") return Iso4217CurrencyCodes.AUD;
            else if (code == "AWG") return Iso4217CurrencyCodes.AWG;
            else if (code == "AZN") return Iso4217CurrencyCodes.AZN;
            else if (code == "BAM") return Iso4217CurrencyCodes.BAM;
            else if (code == "BBD") return Iso4217CurrencyCodes.BBD;
            else if (code == "BDT") return Iso4217CurrencyCodes.BDT;
            else if (code == "BGN") return Iso4217CurrencyCodes.BGN;
            else if (code == "BHD") return Iso4217CurrencyCodes.BHD;
            else if (code == "BIF") return Iso4217CurrencyCodes.BIF;
            else if (code == "BMD") return Iso4217CurrencyCodes.BMD;
            else if (code == "BND") return Iso4217CurrencyCodes.BND;
            else if (code == "BOB") return Iso4217CurrencyCodes.BOB;
            else if (code == "BOV") return Iso4217CurrencyCodes.BOV;
            else if (code == "BRL") return Iso4217CurrencyCodes.BRL;
            else if (code == "BSD") return Iso4217CurrencyCodes.BSD;
            else if (code == "BTN") return Iso4217CurrencyCodes.BTN;
            else if (code == "BWP") return Iso4217CurrencyCodes.BWP;
            else if (code == "BYR") return Iso4217CurrencyCodes.BYR;
            else if (code == "BZD") return Iso4217CurrencyCodes.BZD;
            else if (code == "CDF") return Iso4217CurrencyCodes.CDF;
            else if (code == "CAD") return Iso4217CurrencyCodes.CAD;
            else if (code == "CHE") return Iso4217CurrencyCodes.CHE;
            else if (code == "CHF") return Iso4217CurrencyCodes.CHF;
            else if (code == "CHW") return Iso4217CurrencyCodes.CHW;
            else if (code == "CLF") return Iso4217CurrencyCodes.CLF;
            else if (code == "CLP") return Iso4217CurrencyCodes.CLP;
            else if (code == "CNY") return Iso4217CurrencyCodes.CNY;
            else if (code == "COP") return Iso4217CurrencyCodes.COP;
            else if (code == "COU") return Iso4217CurrencyCodes.COU;
            else if (code == "CRC") return Iso4217CurrencyCodes.CRC;
            else if (code == "CUC") return Iso4217CurrencyCodes.CUC;
            else if (code == "CUP") return Iso4217CurrencyCodes.CUP;
            else if (code == "CVE") return Iso4217CurrencyCodes.CVE;
            else if (code == "CZK") return Iso4217CurrencyCodes.CZK;
            else if (code == "DJF") return Iso4217CurrencyCodes.DJF;
            else if (code == "DKK") return Iso4217CurrencyCodes.DKK;
            else if (code == "DOP") return Iso4217CurrencyCodes.DOP;
            else if (code == "DZD") return Iso4217CurrencyCodes.DZD;
            else if (code == "EGP") return Iso4217CurrencyCodes.EGP;
            else if (code == "ERN") return Iso4217CurrencyCodes.ERN;
            else if (code == "ETB") return Iso4217CurrencyCodes.ETB;
            else if (code == "EUR") return Iso4217CurrencyCodes.EUR;
            else if (code == "FJD") return Iso4217CurrencyCodes.FJD;
            else if (code == "FKP") return Iso4217CurrencyCodes.FKP;
            else if (code == "GBP") return Iso4217CurrencyCodes.GBP;
            else if (code == "GEL") return Iso4217CurrencyCodes.GEL;
            else if (code == "GHS") return Iso4217CurrencyCodes.GHS;
            else if (code == "GIP") return Iso4217CurrencyCodes.GIP;
            else if (code == "GMD") return Iso4217CurrencyCodes.GMD;
            else if (code == "GNF") return Iso4217CurrencyCodes.GNF;
            else if (code == "GTQ") return Iso4217CurrencyCodes.GTQ;
            else if (code == "GYD") return Iso4217CurrencyCodes.GYD;
            else if (code == "HKD") return Iso4217CurrencyCodes.HKD;
            else if (code == "HNL") return Iso4217CurrencyCodes.HNL;
            else if (code == "HRK") return Iso4217CurrencyCodes.HRK;
            else if (code == "HTG") return Iso4217CurrencyCodes.HTG;
            else if (code == "HUF") return Iso4217CurrencyCodes.HUF;
            else if (code == "IDR") return Iso4217CurrencyCodes.IDR;
            else if (code == "ILS") return Iso4217CurrencyCodes.ILS;
            else if (code == "INR") return Iso4217CurrencyCodes.INR;
            else if (code == "IQD") return Iso4217CurrencyCodes.IQD;
            else if (code == "IRR") return Iso4217CurrencyCodes.IRR;
            else if (code == "ISK") return Iso4217CurrencyCodes.ISK;
            else if (code == "JMD") return Iso4217CurrencyCodes.JMD;
            else if (code == "JOD") return Iso4217CurrencyCodes.JOD;
            else if (code == "JPY") return Iso4217CurrencyCodes.JPY;
            else if (code == "KES") return Iso4217CurrencyCodes.KES;
            else if (code == "KGS") return Iso4217CurrencyCodes.KGS;
            else if (code == "KHR") return Iso4217CurrencyCodes.KHR;
            else if (code == "KMF") return Iso4217CurrencyCodes.KMF;
            else if (code == "KPW") return Iso4217CurrencyCodes.KPW;
            else if (code == "KRW") return Iso4217CurrencyCodes.KRW;
            else if (code == "KWD") return Iso4217CurrencyCodes.KWD;
            else if (code == "KYD") return Iso4217CurrencyCodes.KYD;
            else if (code == "KZT") return Iso4217CurrencyCodes.KZT;
            else if (code == "LAK") return Iso4217CurrencyCodes.LAK;
            else if (code == "LBP") return Iso4217CurrencyCodes.LBP;
            else if (code == "LKR") return Iso4217CurrencyCodes.LKR;
            else if (code == "LRD") return Iso4217CurrencyCodes.LRD;
            else if (code == "LSL") return Iso4217CurrencyCodes.LSL;
            else if (code == "LTL") return Iso4217CurrencyCodes.LTL;
            else if (code == "LYD") return Iso4217CurrencyCodes.LYD;
            else if (code == "MAD") return Iso4217CurrencyCodes.MAD;
            else if (code == "MDL") return Iso4217CurrencyCodes.MDL;
            else if (code == "MGA") return Iso4217CurrencyCodes.MGA;
            else if (code == "MKD") return Iso4217CurrencyCodes.MKD;
            else if (code == "MMK") return Iso4217CurrencyCodes.MMK;
            else if (code == "MNT") return Iso4217CurrencyCodes.MNT;
            else if (code == "MOP") return Iso4217CurrencyCodes.MOP;
            else if (code == "MRO") return Iso4217CurrencyCodes.MRO;
            else if (code == "MUR") return Iso4217CurrencyCodes.MUR;
            else if (code == "MVR") return Iso4217CurrencyCodes.MVR;
            else if (code == "MWK") return Iso4217CurrencyCodes.MWK;
            else if (code == "MXN") return Iso4217CurrencyCodes.MXN;
            else if (code == "MXV") return Iso4217CurrencyCodes.MXV;
            else if (code == "MYR") return Iso4217CurrencyCodes.MYR;
            else if (code == "MZN") return Iso4217CurrencyCodes.MZN;
            else if (code == "NAD") return Iso4217CurrencyCodes.NAD;
            else if (code == "NGN") return Iso4217CurrencyCodes.NGN;
            else if (code == "NOK") return Iso4217CurrencyCodes.NOK;
            else if (code == "NIO") return Iso4217CurrencyCodes.NIO;
            else if (code == "NPR") return Iso4217CurrencyCodes.NPR;
            else if (code == "NZD") return Iso4217CurrencyCodes.NZD;
            else if (code == "OMR") return Iso4217CurrencyCodes.OMR;
            else if (code == "PAB") return Iso4217CurrencyCodes.PAB;
            else if (code == "PEN") return Iso4217CurrencyCodes.PEN;
            else if (code == "PGK") return Iso4217CurrencyCodes.PGK;
            else if (code == "PHP") return Iso4217CurrencyCodes.PHP;
            else if (code == "PKR") return Iso4217CurrencyCodes.PKR;
            else if (code == "PLN") return Iso4217CurrencyCodes.PLN;
            else if (code == "PYG") return Iso4217CurrencyCodes.PYG;
            else if (code == "QAR") return Iso4217CurrencyCodes.QAR;
            else if (code == "RON") return Iso4217CurrencyCodes.RON;
            else if (code == "RSD") return Iso4217CurrencyCodes.RSD;
            else if (code == "RUB") return Iso4217CurrencyCodes.RUB;
            else if (code == "RWF") return Iso4217CurrencyCodes.RWF;
            else if (code == "SAR") return Iso4217CurrencyCodes.SAR;
            else if (code == "SBD") return Iso4217CurrencyCodes.SBD;
            else if (code == "SCR") return Iso4217CurrencyCodes.SCR;
            else if (code == "SDG") return Iso4217CurrencyCodes.SDG;
            else if (code == "SEK") return Iso4217CurrencyCodes.SEK;
            else if (code == "SGD") return Iso4217CurrencyCodes.SGD;
            else if (code == "SHP") return Iso4217CurrencyCodes.SHP;
            else if (code == "SLL") return Iso4217CurrencyCodes.SLL;
            else if (code == "SOS") return Iso4217CurrencyCodes.SOS;
            else if (code == "SRD") return Iso4217CurrencyCodes.SRD;
            else if (code == "SSP") return Iso4217CurrencyCodes.SSP;
            else if (code == "STD") return Iso4217CurrencyCodes.STD;
            else if (code == "SVC") return Iso4217CurrencyCodes.SVC;
            else if (code == "SYP") return Iso4217CurrencyCodes.SYP;
            else if (code == "SZL") return Iso4217CurrencyCodes.SZL;
            else if (code == "THB") return Iso4217CurrencyCodes.THB;
            else if (code == "TJS") return Iso4217CurrencyCodes.TJS;
            else if (code == "TMT") return Iso4217CurrencyCodes.TMT;
            else if (code == "TND") return Iso4217CurrencyCodes.TND;
            else if (code == "TOP") return Iso4217CurrencyCodes.TOP;
            else if (code == "TRY") return Iso4217CurrencyCodes.TRY;
            else if (code == "TTD") return Iso4217CurrencyCodes.TTD;
            else if (code == "TWD") return Iso4217CurrencyCodes.TWD;
            else if (code == "TZS") return Iso4217CurrencyCodes.TZS;
            else if (code == "UAH") return Iso4217CurrencyCodes.UAH;
            else if (code == "UGX") return Iso4217CurrencyCodes.UGX;
            else if (code == "USD") return Iso4217CurrencyCodes.USD;
            else if (code == "USN") return Iso4217CurrencyCodes.USN;
            else if (code == "UYI") return Iso4217CurrencyCodes.UYI;
            else if (code == "UYU") return Iso4217CurrencyCodes.UYU;
            else if (code == "UZS") return Iso4217CurrencyCodes.UZS;
            else if (code == "VEF") return Iso4217CurrencyCodes.VEF;
            else if (code == "VND") return Iso4217CurrencyCodes.VND;
            else if (code == "VUV") return Iso4217CurrencyCodes.VUV;
            else if (code == "WST") return Iso4217CurrencyCodes.WST;
            else if (code == "XAF") return Iso4217CurrencyCodes.XAF;
            else if (code == "XAG") return Iso4217CurrencyCodes.XAG;
            else if (code == "XAU") return Iso4217CurrencyCodes.XAU;
            else if (code == "XBA") return Iso4217CurrencyCodes.XBA;
            else if (code == "XBB") return Iso4217CurrencyCodes.XBB;
            else if (code == "XBC") return Iso4217CurrencyCodes.XBC;
            else if (code == "XBD") return Iso4217CurrencyCodes.XBD;
            else if (code == "XCD") return Iso4217CurrencyCodes.XCD;
            else if (code == "XDR") return Iso4217CurrencyCodes.XDR;
            else if (code == "XOF") return Iso4217CurrencyCodes.XOF;
            else if (code == "XPD") return Iso4217CurrencyCodes.XPD;
            else if (code == "XPF") return Iso4217CurrencyCodes.XPF;
            else if (code == "XPT") return Iso4217CurrencyCodes.XPT;
            else if (code == "XSU") return Iso4217CurrencyCodes.XSU;
            else if (code == "XTS") return Iso4217CurrencyCodes.XTS;
            else if (code == "XUA") return Iso4217CurrencyCodes.XUA;
            else if (code == "XXX") return Iso4217CurrencyCodes.XXX;
            else if (code == "YER") return Iso4217CurrencyCodes.YER;
            else if (code == "ZAR") return Iso4217CurrencyCodes.ZAR;
            else if (code == "ZMW") return Iso4217CurrencyCodes.ZMW;
            else if (code == "ZWL") return Iso4217CurrencyCodes.ZWL;
            else return Iso4217CurrencyCodes.Undefined;
        }

        public static string getCurrencyNumCode(Iso4217CurrencyCodes code) {
            return Iso4217Currencies.GetCurrency(code).Code;
        }
        public static string getCurrencyCountryCode(string code) {
            var values = Enum.GetValues(typeof(Iso4217CurrencyCodes)).Cast<Iso4217CurrencyCodes>();

            foreach (var cc in values) {
                if (Iso4217Currencies.GetCurrency(cc).Code == code)
                    return cc.ToString();
            }
            return null;
        }
    }
}
